
version: '3.8'

services:
  movie-dashboard:
    build: .
    ports:
      - "8050:8050"
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
    volumes:
      - ./data:/app/data
      - ./app:/app/app
    restart: unless-stopped
    container_name: movie-dashboard
